# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the required Python packages (ensure you have a requirements.txt file in the same directory)
RUN pip install --no-cache-dir -r requirements.txt

# Run the script when the container launches
CMD ["python", "stream.py"]
